steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/moss-app:latest', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/moss-app:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mos-atomantstudios'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/moss-app:latest'
      - '--region'
      - 'asia-south1'
      - '--service-account'
      - 'cloud-run-gcs-signer@mos-atomantstudios.iam.gserviceaccount.com'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '2'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '20'
      - '--timeout'
      - '900'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=mos-aat,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FLASK_SECRET_KEY=9rHms6H3UDZVQTcIGYTEHfB9uOLz7gGF2M1pzbEaEtoHh8Qys_j_mb2eiNPwp79HxmiCcLXY2mj20aa_dgW7Fw'
      - '--set-env-vars'
      - 'MAX_CONTENT_LENGTH=2147483648'
      - '--set-env-vars'
      - 'REQUEST_SIZE_LIMIT=2147483648'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/moss-app:latest' 