services:
  - type: web
    name: media-action
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y vlc libvlc-dev
      pip install python-vlc==3.0.21203
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    systemPackages:
      - ffmpeg
      - vlc
      - libvlc-dev 